spring.application.name=apollo.pesquisas.novo
spring.data.mongodb.uri=mongodb://localhost:27017/apollopesquisas
spring.data.mongodb.database=apollopesquisas
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.port=8080
spring.security.user.name=admin
spring.security.user.password=adminpassword
spring.security.user.roles=USER

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.mvc.view.prefix=/templates/
spring.thymeleaf.enabled=true
spring.mvc.view.suffix=.html
spring.thymeleaf.cache=false
logging.level.org.springframework.security=DEBUG

#ESQUECI MINHA SENHA
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=apollopesquisas@gmail.com
spring.mail.password=stlp jenx gkyz boze
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=apollopesquisas@gmail.com
apollo.domain=${DOMAIN:http://localhost:8080}




