spring.application.name=apollo.pesquisas
spring.data.mongodb.uri=mongodb://localhost:27017/apollopesquisas
spring.data.mongodb.database=apollopesquisas
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.port=8080
spring.security.user.name=admin
spring.security.user.password=adminpassword
spring.security.user.roles=USER
